---
openapi: 3.0.3
info:
  title: Nogarap API
  description: API documentation for Nogarap.
  version: "1.0.0"
tags:
  - name: Auth
    description: Endpoint relativi ad autenticazione e registrazione
paths:
  /api/v1/signup/create:
    get:
      tags:
        - Auth
      summary: Recupera informazioni sul signup
      description: Ritorna una descrizione dell’endpoint di registrazione.
      responses:
        "200":
          description: Informazioni sull’endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usa POST per registrarti
    post:
      tags:
        - Auth
      summary: Registrazione utente
      parameters:
        - name: device_uuid
          in: query
          required: true
          description: |
            Serial number of the USB device.
          schema:
            type: string
            format: text
        - name: usb_public_key
          in: query
          required: true
          description: |
            Public key of USB device.
          schema:
            type: string
            format: text
        - name: username
          in: query
          required: true
          description: |
            Username of the new user.
          schema:
            type: string
            format: text
        - name: POH
          in: query
          required: true
          description: |
            Proof Of Hardware to avoid malicious usage of the endpoint
          schema:
            type: string
            format: text
      responses:
        '201':
          description: User created, solve pow and Captcha to enable.
          content:
            application/json:
              schema:
                description: captcha and pow
                required:
                  - captcha
                  - pow
                properties:
                  captcha:
                    description: this proves you're not a robot.
                    type: string
                  pow:
                    description: this is the pow to paste to the terminal.
                    type: string
        '400':
          description: Bad request.

  /api/v1/signup/validate:
    post:
      tags: 
        - Auth
      summary: Conferma e abilità l'utente
      description: Contolla che i valori dati dall'utente siano effettivi e nel caso abilita l'utente.
      parameters:
        - name: POW
          in: query
          required: true
          description: |
            Proof Of Work used to avoid DDos
          schema:
            type: string
            format: text
        - name: Captcha
          in: query
          required: true
          description: |
            Proof of not being a bot.
          schema:
            type: string
            format: text
        - name: username
          in: query
          required: true
          description: |
            Username of the client user.
          schema:
            type: string
            format: text
        - name: POH
          in: query
          required: true
          description: |
            Proof Of Hardware to avoid malicious usage of the endpoint
          schema:
            type: string
            format: text
      responses:
        '200':
          description: Ok. User validated succesfully.
        '402':
          description: Unauthorized. Username not present or wrong Captcha and pow.
        '419':
          description: Page Expired. You took too long to solve pow and Captcha.
